services:
  gateway:
    build: ./gateway
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  jwt_auth:
    build: ./jwt_auth
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy
  orders:
    build: ./orders
    ports:
      - 8082:8082
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: VerySecureUserPassword
      POSTGRES_DB: restaurant_users,restaurant_orders
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d restaurant_orders"]
      interval: 5s
      timeout: 5s
      retries: 20